import { Category } from '../types';

// Keywords for auto-categorization of events
export const categoryKeywords: Record<Exclude<Category, Category.UNCATEGORIZED>, string[]> = {
  [Category.WORK]: [
    'meeting',
    'standup',
    'sync',
    'review',
    'interview',
    'deadline',
    'presentation',
    'client',
    'call',
    '1:1',
    'sprint',
    'retro',
    'planning',
    'workshop',
    'conference',
    'scrum',
    'demo',
    'office',
    'work',
    'project',
  ],
  [Category.PLAY]: [
    'party',
    'game',
    'movie',
    'dinner',
    'drinks',
    'concert',
    'hangout',
    'netflix',
    'birthday',
    'bbq',
    'festival',
    'vacation',
    'trip',
    'bar',
    'club',
    'brunch',
    'fun',
    'friends',
    'hang',
  ],
  [Category.HEALTH]: [
    'gym',
    'workout',
    'yoga',
    'run',
    'doctor',
    'dentist',
    'therapy',
    'meditation',
    'physio',
    'swim',
    'hike',
    'cycling',
    'fitness',
    'checkup',
    'massage',
    'exercise',
    'walk',
    'jog',
    'lift',
    'crossfit',
  ],
  [Category.ROMANCE]: [
    'date',
    'anniversary',
    'valentines',
    'dinner with',
    'partner',
    'boyfriend',
    'girlfriend',
    'spouse',
    'bae',
    'hubby',
    'wifey',
    'romantic',
    'love',
  ],
  [Category.STUDY]: [
    'class',
    'course',
    'lecture',
    'study',
    'exam',
    'test',
    'tutorial',
    'homework',
    'reading',
    'learning',
    'lesson',
    'bootcamp',
    'training',
    'certification',
    'school',
    'university',
    'college',
  ],
};
